### ISSUE TITLE
Difficult motol control

### ISSUE THREAD

**Issue by derba** [ev3go/ev3dev#32]
I am new to both EV3 and Go. I just wanted to play a bit with motor control (large motor on outB). While it was easily in Python...

```python
#!/usr/bin/env python3
from time import sleep
from ev3dev.ev3 import *

motor_left = LargeMotor('outB')
motor_left.run_direct(duty_cycle_sp=100)
sleep(0.5)
motor_left.run_direct(duty_cycle_sp=0)
```

The same went shockingly difficult in Go...

```go
package main

import (
	"time"
	"github.com/ev3go/ev3dev"
)

func main() {
	const driver = "lego-ev3-l-motor"
	m, err := ev3dev.TachoMotorFor("outB", driver)
	if err != nil {
		panic(err)
	}
	err = m.Command("reset").Err()
	if err != nil {
		panic(err)
	}
	err = m.SetPolarity("normal").Err()
	if err != nil {
		panic(err)
	}
	maxSpeed, err := m.MaxSpeed()
	if err != nil {
		panic(err)
	}
	err = m.SetSpeedSetpoint(maxSpeed).Err()
	if err != nil {
		panic(err)
	}
	err = m.Command("run-forever").Err()
	if err != nil {
		panic(err)
	}
	time.Sleep(500 * time.Millisecond)
	err = m.Command("stop").Err()
	if err != nil {
		panic(err)
	}
}
```

I can write a Python `run_direct`-like function in Go, of course. But I wonder whether there is such a function, that I could use out-of-the-box.

**Comment by kortschak** [comment]
The library allows you to write the same as above in fluent style (this is the reason for the `Err` method).

Note that the Go code you provided is not the same as the python code since one is running the motor in direct mode and the Go code is using the "run-timed" command instead of the "run-direct" command. You should check [the ev3dev tachomotor docs](http://www.ev3dev.org/docs/drivers/tacho-motor-class/) for the difference between these. However, rewriting your code to use the preferred style:

```
package main

import (
	"time"

	"github.com/ev3go/ev3dev"
)

func main() {
	const driver = "lego-ev3-l-motor"
	m, err := ev3dev.TachoMotorFor("outB", driver)
	if err != nil {
		panic(err)
	}

	maxSpeed, err := m.MaxSpeed()
	if err != nil {
		panic(err)
	}

	err = m.Command("reset").
		SetPolarity(ev3dev.Normal).
		SetSpeedSetpoint(maxSpeed).
		Command("run-forever").Err()
	if err != nil {
		panic(err)
	}

	time.Sleep(500 * time.Millisecond)

	err = m.Command("stop").Err()
	if err != nil {
		panic(err)
	}
}
```

I should check since I don't use the python librarirs, should you be setting normal polarity, and how are you specifying `run-forever` behaviour?

You can also write the Go code above as

```
package main

import (
	"time"

	"github.com/ev3go/ev3dev"
)

func main() {
	const driver = "lego-ev3-l-motor"
	m, err := ev3dev.TachoMotorFor("outB", driver)
	if err != nil {
		panic(err)
	}

	maxSpeed, err := m.MaxSpeed()
	if err != nil {
		panic(err)
	}

	// Setting polarity to normal is not required given we are doing "reset".
	err = m.Command("reset").
		SetSpeedSetpoint(maxSpeed).
		SetTimeSetpoint(500 * time.Millisecond).
		Command("run-timed").Err()
	if err != nil {
		panic(err)
	}

	// Could omit this if the only behaviour wanted was to run motor for half second..
	// This just prevents program termination prior to motor running completion.
	ev3dev.Wait(m, ev3dev.Running, 0, ev3dev.Running, false, time.Second)
}
```

Finally, here is the actual translation of the python code. Note that it would be possible for the Go package to have pretty much exactly the same behaviour as the python code if I panicked within the library. This is not normal Go practice; the fluent style used is a more helpful approximation.

```
package main

import (
	"time"

	"github.com/ev3go/ev3dev"
)

func main() {
	const driver = "lego-ev3-l-motor"
	m, err := ev3dev.TachoMotorFor("outB", driver)
	if err != nil {
		panic(err)
	}

	err = m.Command("reset").
		SetDutyCycleSetpoint(100).
		Command("run-directed").Err()
	if err != nil {
		panic(err)
	}
	time.Sleep(500 * time.Millisecond)
	err = m.Command("stop").Err()
	if err != nil {
		panic(err)
	}
}
```

The reason there is not a run direct function out of the box is that I have not needed one. If there is a need it would go in `motorutil` rather than in `ev3dev`. From the last example, it does not look onerous to use the code above.

**Comment by derba** [comment]
@kortschak, Thank you. Really nice examples. I think SetTimeSetpoint is the closest one of my intention. Actually what I want to create is a simple obstacle avoiding robot using IR sensor. And an emergency stop button (probably having its own goroutine) calling exit() and making sure that all the motors stop.

I think the examples showed that it is not that difficult to do motor control. So the issue can be closed.

**Comment by kortschak** [comment]
As an exercise in golf:

```
package main

import (
	"time"

	"github.com/ev3go/ev3dev"
)

func main() {
	const driver = "lego-ev3-l-motor"
	m, err := ev3dev.TachoMotorFor("outB", driver)
	if err != nil {
		panic(err)
	}

	must(SetDutyCycleSetpoint(100).Command("run-directed").Err())
	time.Sleep(time.Second / 2)
	must(m.Command("stop").Err())
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
```

**Comment by derba** [comment]
Go has panic(), runtime.Goexit(), log.Fatal() as well as os.Exit(). But nothing like [trap ERR of bash](http://unix.stackexchange.com/a/39660). And probably Go is fine that way. Just the holy Go formatting makes the code unreadable, distracting your attention from the main logic.

In Perl you write `f() or die;` in C `if (f() < 0) exit(1);` And `func must()` makes error handling one-liner in Go, so you can focus on the business logic. Thank you for pointing this out.

**Comment by kortschak** [comment]
Be wary of overuse of a must-like function. They have their place, but can easily be over used. The sticky error idiom used in the ev3dev package is an approach that allows minimisation of `if err != nil {` lines while still handling the errors.

Note that your C example is identical to the Go approach, `if f() != nil { os.Exit(1) }`, when f returns only an error.

You can simulate error trapping with panic/defer/recover, but it is a code smell if over used. Here is an example that uses a user-defined error type that captures the erroring location.

```
func f() {
	panic(Error{message: "bad thing", stack: callers()})
}

func main() {
	defer func() {
		r := recover()
		if r != nil {
			fmt.Println(r)
		}
	}()

	f() // panics for error cases
}
```

Full code [here](https://play.golang.org/p/vNpZoRB-9S). Note that there are packages to handle this approach to errors, and the ev3dev package captures the error location and will someday provide the possibility of printing the stack trace (it just needs the plumbing), though does already print the user call location of the error.

However, this is off-topic for ev3dev and is a more general Go issue. The approach is a design decision rather than a design failure. Action at a distance (exceptions and error traps) make reasoning about code flow harder.
